name: Generate Thumbnails

on:
  schedule:
    - cron: '0 0 * * *'  # 12:00 AM UTC daily
    - cron: '0 9 * * *'  # 9:00 AM UTC daily
  workflow_dispatch:      # Manual trigger from GitHub
  repository_dispatch:    # Trigger from external API/iPhone

jobs:
  generate-thumbnails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Set up Firebase credentials
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-key.json
      
    - name: Run thumbnail generator
      run: python generate_thumbnails.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-key.json
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-generated thumbnails $(date)"
        git push || echo "No changes to push"